# Generated by Django 5.1.7 on 2025-03-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itemrequest_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='code_request',
        ),
        migrations.AddField(
            model_name='studentborrow',
            name='code_request',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
